// "use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { ChakraProvider } from "@chakra-ui/react";
const inter = Inter({ subsets: ["latin"] });
import "@rainbow-me/rainbowkit/styles.css";
import { hardhat } from "wagmi/chains";
import { getDefaultWallets, RainbowKitProvider } from "@rainbow-me/rainbowkit";
import { configureChains, createConfig, WagmiConfig } from "wagmi";
import { mainnet, polygon, optimism, arbitrum, zora } from "wagmi/chains";
// import { alchemyProvider } from "wagmi/providers/alchemy";
import { publicProvider } from "wagmi/providers/public";

//BUGS : pb de modules et de config !!!!!!!!!!!!

// import { env } from "@/next.config";
// require("dotenv").config();
//
const { chains, publicClient } = configureChains(
  [hardhat], //[mainnet, polygon, optimism, arbitrum, zora],
  [
    // alchemyProvider({ apiKey: process.env.ALCHEMY_ID }),
    publicProvider(),
  ]
);
const { connectors } = getDefaultWallets({
  appName: "My RainbowKit App",
  projectId: "58c04492c719d70985bce45898088b9", //'YOUR_PROJECT_ID',
  chains,
});
const wagmiConfig = createConfig({
  autoConnect: false, //sinon pb hydratationtrue,
  connectors,
  publicClient,
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <WagmiConfig config={wagmiConfig}>
        <RainbowKitProvider chains={chains}>
          <ChakraProvider>
            <body className={inter.className}>{children}</body>
          </ChakraProvider>
        </RainbowKitProvider>
      </WagmiConfig>
    </html>
  );
}
