// "use client";
import "./globals.css";
import { ChakraProvider } from "../node_modules/@chakra-ui/react";
import { WalletProvider } from "../context/walletProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <WalletProvider>
          <ChakraProvider>{children}</ChakraProvider>
        </WalletProvider>
      </body>
    </html>
  );
}
