"use client"
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { Flex, Text } from '@chakra-ui/react'
import Link from 'next/link'
import Head from 'next/head'

export const Header = () => {
    return (
        <>
            <Head>
                <title>Minting DApp</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Flex h="15vh" p="2rem" justifyContent="space-between" alignItems="center">
                <Text>Minting DApp</Text>
                <ConnectButton />
            </Flex>
        </>
    )
}